server:
  port: 8081
  error:
    include-message: always

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/bankappdb
    username: user
    password: password
  data:
    r2dbc:
      repositories:
        enabled: true

web-client:
  url: http://localhost:8082

logging:
  level:
    web: DEBUG
