bankapp:
  transaction:
    trx-id-prefix: 30
    trx-id-length: 10
  card:
    add-card: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankappdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: INFO

management:
  server.port: 8082
  endpoints:
    web:
      exposure:
        include: env,health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    java:
      enabled: true